# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20160222_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
