# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_auto_20160222_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(max_length=20)),
                ('temporary_address', models.CharField(max_length=20)),
                ('permanent_address', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=20)),
            ],
        ),
    ]
