# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 03:09
from __future__ import unicode_literals

import credentials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0010_auto_20160331_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='upload_cv',
            field=models.FileField(null=True, upload_to=credentials.models.get_upload_filename),
        ),
    ]
