# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 17:50
from __future__ import unicode_literals

import credentials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0012_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='links',
        ),
        migrations.AddField(
            model_name='photo',
            name='imagename',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='upload',
            field=models.ImageField(null=True, upload_to=credentials.models.get_upload_imagename),
        ),
    ]
