# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0013_auto_20160419_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='imagename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
