# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0014_auto_20160419_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500, null=True)),
                ('url', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
