# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 02:33
from __future__ import unicode_literals

import credentials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0015_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='headoffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('plot_number', models.CharField(max_length=30, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=30, null=True)),
                ('Pincode', models.IntegerField(null=True)),
                ('Country', models.CharField(max_length=30, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='jobprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20, null=True)),
                ('CPI_cut_off', models.FloatField(max_length=10)),
                ('Branches', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('upload', models.ImageField(null=True, upload_to=credentials.models.get_upload_imagename)),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('upload', models.ImageField(null=True, upload_to=credentials.models.get_upload_imagename)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('plot_number', models.CharField(max_length=30, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=30, null=True)),
                ('Pincode', models.IntegerField(null=True)),
                ('Country', models.CharField(max_length=30, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('plot_number', models.CharField(max_length=30, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=30, null=True)),
                ('Pincode', models.IntegerField(null=True)),
                ('Country', models.CharField(max_length=30, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
