# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0016_benefits_headoffice_jobprofile_logo_media_sales_office_search_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='search',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='permanent_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='temporary_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='internships',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
