# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0018_auto_20160422_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='description',
            new_name='project2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='position',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projects_related_url',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='title',
        ),
        migrations.AddField(
            model_name='projects',
            name='project1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
