# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0019_auto_20160422_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLACEMENTS_DATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalstudents', models.IntegerField(default=0, null=True)),
                ('totalpercentageplaced', models.IntegerField(default=0, null=True)),
                ('totalpostgraduate', models.IntegerField(default=0, null=True)),
                ('undergradplaced', models.IntegerField(default=0, null=True)),
                ('totalundergraduate', models.IntegerField(default=0, null=True)),
                ('postgradplaced', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='internships',
            new_name='internship',
        ),
        migrations.RenameModel(
            old_name='languages',
            new_name='language',
        ),
        migrations.RenameModel(
            old_name='projects',
            new_name='project',
        ),
    ]
