# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0022_auto_20160426_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_info',
            name='user',
        ),
        migrations.DeleteModel(
            name='Extra_Info',
        ),
    ]
